name: Run and Commit Auto Script

on:
  push:
    branches:
      - origin main
  schedule:
    - cron: "1 * * * *"

jobs:
  bots:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v1

      - name: Run auto.sh script
        run: |
          chmod +x auto.sh
          ./auto.sh

      - name: "Commit"
        uses: EndBug/add-and-commit@v4
        with:
          author_name: lonewolfyx
          author_email: 877085893@qq.com
          message: "auto push commit"
          add: "."

        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
